version: '3.9'
name: 'frontend'

services:
  main_db:
    image: mysql:latest
    container_name: main_db
    environment:
      MYSQL_DATABASE: main
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33064:3306
  
  main:
    build:
      context: .docker
      dockerfile: Dockerfile
    command: /bin/bash -c "./.docker/start.sh"
    volumes:
      - .:/app
      # - /app/vendor/
    ports:
      - 8001:8000
    depends_on:
      - main_db

  main_queue:
    build:
      context: .docker
      dockerfile: Dockerfile
    command: /bin/bash -c "./.docker/queue.sh"
    depends_on:
      - main_db