version: '3.9'
name: 'backend'

services:
  admin:
    build:
      context: .docker
      dockerfile: Dockerfile
    command: /bin/bash -c "./.docker/start.sh"
    volumes:
      - .:/app
      # - /app/vendor/
    ports:
      - 8000:8000
    depends_on:
      - admin_db

  admin_queue:
    build:
      context: .docker
      dockerfile: Dockerfile
    command: /bin/bash -c "./.docker/queue.sh"
    depends_on:
      - admin_db
      - admin

  admin_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: admin
      # MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33063:3306