version: '3.9'
name: 'backend'

services:
  admin:
    build:
      context: .docker
      dockerfile: Dockerfile
    command: /bin/bash -c "./.docker/start.sh"
    volumes:
      - .:/app
      # - /app/vendor/
    ports:
      - 8000:8000
    depends_on:
      - admin_db
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 10s
      timeout: 10s
      retries: 15

  admin_queue:
    build:
      context: .docker
      dockerfile: Dockerfile
    command: /bin/bash -c "php artisan rabbitmq:consume"
    volumes:
      - .:/app
    depends_on:
      admin:
        condition: service_healthy

  admin_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33063:3306